<?php

namespace AppBundle\Repository;

/**
 * CreneauRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CreneauRepository extends \Doctrine\ORM\EntityRepository
{
    public function findWithRestCapacity(\DateTime $date, string $postalCode, int $minRestCapacity = 0) {

        $result = $this->getEntityManager()
            ->createQuery(
                'SELECT c, (c.capacity - SUM(co.quantite)) AS restCapacity 
                    FROM AppBundle:Creneau c
                    LEFT JOIN AppBundle:Commande co WITH c.id = co.creneau
                    where c.date = :date
                    and c.postalCode = :postalCode'
            )
            ->setParameter(':date', $date->format('Y-m-d'))
            ->setParameter(':postalCode', $postalCode)
            ->getSingleResult();

        $restCapacity = $result['restCapacity'] ?? $result[0]->getCapacity();
        $result['restCapacity'] = $restCapacity;

        if ($minRestCapacity > $restCapacity) {
            return null;
        }

        return $result;
    }

    public function findByIdWithRestCapacity(int $id, int $minRestCapacity = 0) {

        $result = $this->getEntityManager()
            ->createQuery(
                'SELECT c, (c.capacity - SUM(co.quantite)) AS restCapacity 
                    FROM AppBundle:Creneau c
                    LEFT JOIN AppBundle:Commande co WITH c.id = co.creneau
                    where c.id = :id'
            )
            ->setParameter(':id', $id)
            ->getSingleResult();

        $restCapacity = $result['restCapacity'] ?? $result[0]->getCapacity();
        $result['restCapacity'] = $restCapacity;

        if ($minRestCapacity > $restCapacity) {
            return null;
        }

        return $result;
    }
}
