# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
  truckday_importer:
    class:     AppBundle\Importer\TruckDayImporter
    autowire: true

  calendar_service:
    class:     AppBundle\Service\CalendarService
    autowire: true

  date_service:
    class:     AppBundle\Service\DateService
    autowire: true

  truckday_manager:
    class: AppBundle\Manager\TruckDayManager
    autowire: true

  command_manager:
    class: AppBundle\Manager\CommandManager
    autowire: true

  truckday_repository:
    class: AppBundle\Repository\TruckDayRepository
    factory: ['@doctrine.orm.entity_manager', getRepository]
    arguments:
      - AppBundle\Entity\TruckDay

  command_repository:
    class: AppBundle\Repository\CommandeRepository
    factory: ['@doctrine.orm.entity_manager', getRepository]
    arguments:
      - AppBundle\Entity\Commande
