# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
  truckday_importer:
    class:     AppBundle\Importer\TruckDayImporter
    arguments:
      truckDayManager: "@truckday_manager"

  calendar_service:
    class:     AppBundle\Service\CalendarService
    arguments:
      truckDayManager: "@truckday_manager"
      commandManager: "@command_manager"
      dateService: "@date_service"

  date_service:
    class:     AppBundle\Service\DateService

  truckday_manager:
    class: AppBundle\Manager\TruckDayManager
    arguments:
      truckDayRepository: "@truckday_repository"
      entityManager: "@doctrine.orm.entity_manager"

  command_manager:
    class: AppBundle\Manager\CommandManager
    arguments:
      entityManager: "@doctrine.orm.entity_manager"

  truckday_repository:
    class: AppBundle\Repository\TruckDayRepository
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments:
      - AppBundle\Entity\TruckDay

    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
